### ISSUE TITLE
Add main PCB files to repository

### ISSUE THREAD

**Issue by LimesKey** [Abillow1/Affordable-Quality-Slime-Project-AQSP-#20]
where are the main pcb files??? I want to see the actual pcb

**Comment by Abillow1** [comment]
They are in releases, PCB Prototype A3, about to release A4. I will give you the link in a moment

**Comment by Abillow1** [comment]
https://github.com/Abillow1/Affordable-Quality-Slime-Project-AQSP-/releases/tag/PCB-Prototype-A4

**Comment by Abillow1** [comment]
Oh and for clarity, I haven't added the PCB or case files to the main repository yet as they are still in progress; I'm putting them in dedicated releases.

**Comment by Abillow1** [comment]
o
